config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'static_pages/index'

  resources :bugs do
      resources :comments
  end
  root 'welcome#index'
end

app/models/bug.rb
class Bug < ActiveRecord::Base
    has_many    :comments, dependent: :destroy
    validates   :title, presence: true,
                length: { minimum: 5}
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :bug
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
http_basic_authenticate_with name: "hello", password: "world", except: [:index]
    def index
        @bugs = Bug.all
    end

    def show
        @bug = Bug.find(params[:id])
    end

    def new
        @bug = Bug.new
    end

    def destroy
        @bug = Bug.find(params[:id])
        @bug.destroy

        redirect_to bugs_path
    end

    def edit
        @bug = Bug.find(params[:id])
    end

    def update
        @bug = Bug.find(params[:id])
        if @bug.update(bug_params)
            redirect_to @bug
        else
            render 'edit'
        end
    end

    def create
        #render plain: params[:bug].inspect
        #@bug = Bug.new(params.require(:bug).permit(:title, :text))
        @bug = Bug.new(bug_params)
        if @bug.save
            redirect_to @bug
        else
            render 'new'
        end
    end

    private
        def bug_params
            params.require(:bug).permit(:title, :text)
        end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
http_basic_authenticate_with name: "login", password: "lol", only: :destroy
    def create
        @bug = Bug.find(params[:bug_id])
        @comment = @bug.comments.create(comment_params)
        redirect_to bug_path(@bug)
    end

    def destroy
        @bug = Bug.find(params[:bug_id])
        @comment = @bug.comments.find(params[:id])
        @comment.destroy
        redirect_to bug_path(@bug)
    end

    private
        def comment_params
            params.require(:comment).permit(:commenter, :body)
        end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    layout 'about'
  def index

  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bugs_helper.rb
module BugsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bugs/_form.html.erb
<%= form_for @bug do |f| %>

    <% if @bug.errors.any? %>
        <div id="error_explanation">
            <h2>
                <%= pluralize(@bug.errors.count, "error") %> prohibited this bug from being published:
            </h2>
            <ul>
                <% @bug.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <p>
        <%= f.label :title %><br/>
        <%= f.text_field :title %>
    </p>

    <p>
        <%= f.label :text %><br/>
        <%= f.text_area :text %>
    </p>

    <p>
        <button><%= f.submit %></button>
    </p>
<% end %>

app/views/bugs/edit.html.erb
<h1>Edit Bug</h1>

<%= render 'form' %>

<%= link_to "Back", bugs_path %>

app/views/bugs/index.html.erb
<%= link_to "Nouveau bug", new_bug_path %>
<h1>Listing Bugs</h1>
<table class="table table-bordered">
    <tr>
        <th>
            Title
        </th>
        <th>
            Text
        </th>
        <th colspan="3">

        </th>
    </tr>
    <% @bugs.each do |bug| %>
        <tr>
            <td>
                <%= bug.title %>
            </td>
            <td>
                <%= bug.text %>
            </td>
            <td>
                <button class="btn btn-info"><%= link_to 'Show', bug_path(bug) %></button>
            </td>
            <td>
                <%= link_to 'Edit', edit_bug_path(bug) %>
            </td>
            <td>
                <button class="btn btn-danger"><%= link_to 'Destroy', bug_path(bug),
                    method: :delete,
                    date: { confirm: 'Are you sure?'} %></button>
            </td>
        </tr>
    <% end %>
</table>

app/views/bugs/new.html.erb
<h1>Bugs / New</h1>

<%= render 'form' %>

<%= link_to "Back", bugs_path %>

app/views/bugs/show.html.erb
<p>
    <strong>Title: </strong>
    <%= @bug.title %>
</p>
<p>
    <strong>Text: </strong>
    <%= @bug.text %>
</p>
<h2>Comments</h2>
<%= render @bug.comments %>

<h2>Add a comment : </h2>
<%= render 'comments/form' %>

<button class="btn"><%= link_to "Edit", edit_bug_path(@bug) %></button>
<button class="btn"><%= link_to "Back", bugs_path %></button>

app/views/comments/_comment.html.erb
<p>
    <strong>Commenter</strong>
    <%= comment.commenter %>
</p>

<p>
    <strong>Comment :</strong>
    <%= comment.body %>
</p>

<p>
    <%= link_to 'Destroy Comment', [comment.bug, comment],
                method: :delete,
                data: { confirm: 'Are you sure?'} %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@bug, @bug.comments.build]) do |f| %>
    <p>
        <%= f.label :commenter %><br/>
        <%= f.text_field :commenter %>
    </p>

    <p>
        <%= f.label :body %><br/>
        <%= f.text_area :body %>
    </p>

    <p>
        <%= f.submit %>
    </p>
<% end %>

app/views/layouts/about.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Partiel Curtis</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', :async => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <nav class="navbar navbar-default">
      <div class="container-fluid aboutnav">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button><%= link_to "Home", controller: "welcome" %></button>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="linkli"><%= link_to "Liste Bugs", {controller: "bugs"} , :class=>"aboutlink" %></li>
            <li class="linkli"><%= link_to "A propos", {controller: "static_pages"} , :class=>"aboutlink"%></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
<%= yield %>
<div class="footer">
    Created by Weyoz
</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Partiel Curtis</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', :async => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button><%= link_to "Home", controller: "welcome" %></button>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><%= link_to "Liste Bugs", controller: "bugs" %></li>
            <li><%= link_to "A propos", controller: "static_pages" %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Link</a></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
<%= yield %>
<div class="footer">
    Created by Weyoz
</div>
</body>
</html>

app/views/static_pages/index.html.erb
<h1 class="abouth">This is a static page</h1>
<p class="aboutp">This ruby app was created by Weyoz</p>

<%= link_to 'Back to the website', {controller: 'welcome'} , :class=>"linkback"%>

app/views/welcome/index.html.erb
<h1>Voici mon site de partiel :)</h1>
<div class="panel panel-info">
    <p>
        Vous pouvez voir dans la bar de navigation les liens vers les differentes page de mon application ruby
    </p>

</div>